import { render, screen } from "@testing-library/react"
import RootLayout, { metadata } from "../layout"

// Mock reutilizable del componente Sidebar
jest.mock("@/components/atomic-design/organism/navigate", () => ({
  Sidebar: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="sidebar">{children}</div>
  ),
}))

// Mocks específicos para este test
jest.mock("../utils/functions", () => ({
  monofur: {
    variable: "font-monofur",
  },
}))

jest.mock("@/components/atomic-design/organism/navigate/sidebar/utils", () => ({
  SIDEBAR_DATA: {
    user: { name: "test", email: "test@test.com", avatar: "/avatar.jpg" },
    navMain: [],
    navSecondary: [],
    chats: [],
  },
}))

// Suprimir el warning de React sobre <html> en tests
const originalError = console.error
beforeAll(() => {
  console.error = (...args: unknown[]) => {
    if (
      typeof args[0] === "string" &&
      args[0].includes("In HTML, <html> cannot be a child of <div>")
    ) {
      return
    }
    originalError.call(console, ...args)
  }
})

afterAll(() => {
  console.error = originalError
})

describe("RootLayout", () => {
  it("should render the layout with children", () => {
    const { container } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )
    // Verificar que el contenido se renderiza
    expect(container.textContent).toContain("Test Content")
  })

  it("should render Sidebar component", () => {
    render(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    )
    const sidebar = screen.getByTestId("sidebar")
    expect(sidebar).toBeInTheDocument()
  })

  it("should render children inside Sidebar", () => {
    render(
      <RootLayout>
        <div data-testid="child">Test Content</div>
      </RootLayout>
    )
    const child = screen.getByTestId("child")
    expect(child).toBeInTheDocument()
    expect(child).toHaveTextContent("Test Content")
  })

  it("should export metadata", () => {
    // Verificar que el layout exporta metadata
    expect(metadata).toBeDefined()
    expect(metadata).toHaveProperty("title")
    expect(metadata).toHaveProperty("description")
  })

  it("should have correct metadata values", () => {
    expect(metadata.title).toBe("Create Next App")
    expect(metadata.description).toBe("Generated by create next app")
  })
})

