/**
 * @file layout.ts
 * @description Layout principal de la aplicación.
 */

// Import of components custom
import { Sidebar } from "@/components/atomic-design/organism/navigate";

// Import of utilities
import { monofur } from "@/app/utils/functions";
import "./globals.css";

// Import of types
import type { Metadata } from "next";

// Import of utilities
import { SIDEBAR_DATA } from "@/components/atomic-design/organism/navigate/sidebar/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${monofur.variable} antialiased`}
      >
        <Sidebar data={SIDEBAR_DATA}>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
